In [1]:
from sympy import *
import matplotlib.pyplot as plt
import numpy as np
import torch

In [5]:
from sympy.abc import *
init_printing()

In [19]:
a,b

(tensor([[ 0.1348,  2.0245, -0.1113,  0.4927],
         [ 0.3814, -0.7909,  0.7511, -0.0746],
         [-0.5747, -0.4016,  1.9392, -0.1531]], requires_grad=True),
 tensor([[-0.2774,  1.0242, -0.3862,  0.4580,  0.4483],
         [-0.7322, -0.0132,  0.3465, -0.3648, -1.3270],
         [ 0.1462, -0.4332,  0.5139, -1.1970,  0.5079],
         [-0.6693, -0.0869, -0.5298, -0.6967, -1.7185]], requires_grad=True))

In [44]:
a = torch.randn(3,4,requires_grad=True)
b = torch.randn(4,5,requires_grad=True)
c = torch.randn(5,requires_grad =True)

In [45]:
h1 = a@b 
h2 = h1 + c
h3 = h2**2
s = h3.sum()
for i in [h1, h2, h3,s]:i.retain_grad()
s.backward()

In [53]:
for i in [s,h3,h2,h1,c,a,b]:print(i.grad,"\n")

tensor(1.) 

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]) 

tensor([[-5.3214, -0.2512,  1.8437, -0.8867,  2.5466],
        [-0.6021,  4.7449, 10.2477,  1.9859,  1.7672],
        [-6.2730,  4.4697,  0.5618, -3.7994,  4.1503]]) 

tensor([[-5.3214, -0.2512,  1.8437, -0.8867,  2.5466],
        [-0.6021,  4.7449, 10.2477,  1.9859,  1.7672],
        [-6.2730,  4.4697,  0.5618, -3.7994,  4.1503]]) 

tensor([-12.1965,   8.9634,  12.6532,  -2.7003,   8.4641]) 

tensor([[ -1.1196,   1.3536,  -4.1410,   8.6050],
        [  3.4618, -30.5656,  11.2763,  19.6405],
        [  4.2650,   7.3033,  -7.7193,  16.3720]]) 

tensor([[-5.0178,  8.9532,  7.2192, -2.5765,  4.8580],
        [-2.0650, -0.6357, -6.3914, -3.0633,  0.6528],
        [ 5.5851,  6.1121, 15.4570,  5.6036, -0.7169],
        [-9.8312,  9.2475, 10.5895, -2.8987,  7.3402]]) 



In [66]:
2*h2 , h2.grad

(tensor([[-5.3214, -0.2512,  1.8437, -0.8867,  2.5466],
         [-0.6021,  4.7449, 10.2477,  1.9859,  1.7672],
         [-6.2730,  4.4697,  0.5618, -3.7994,  4.1503]], grad_fn=<MulBackward0>),
 tensor([[-5.3214, -0.2512,  1.8437, -0.8867,  2.5466],
         [-0.6021,  4.7449, 10.2477,  1.9859,  1.7672],
         [-6.2730,  4.4697,  0.5618, -3.7994,  4.1503]]))

In [65]:
h2.sum(axis = 0) * 2, c.grad

(tensor([-12.1965,   8.9634,  12.6532,  -2.7003,   8.4641],
        grad_fn=<MulBackward0>),
 tensor([-12.1965,   8.9634,  12.6532,  -2.7003,   8.4641]))

In [68]:
h1

tensor([[-1.0890,  0.1827, -0.1059,  0.4010,  0.6593],
        [ 1.2707,  2.6807,  4.0961,  1.8373,  0.2696],
        [-1.5648,  2.5431, -0.7469, -1.0554,  1.4612]], grad_fn=<MmBackward0>)

In [71]:
a

tensor([[-0.5435, -0.1466, -0.7217,  0.4042],
        [ 0.7370, -0.6255,  1.6622,  0.8982],
        [ 1.1902,  0.5135, -0.4376,  1.1381]], requires_grad=True)

In [72]:
b

tensor([[ 0.1554,  0.9865, -0.0154, -0.3678, -0.1345],
        [-0.5368, -0.7728, -2.3646, -1.8600,  0.3979],
        [ 0.9882,  0.0382,  1.1183,  0.3380, -0.2494],
        [-0.9153,  1.5662,  0.8568,  0.4266,  1.1491]], requires_grad=True)

In [75]:
a[0] @ b[:,0]

tensor(-1.0890, grad_fn=<DotBackward0>)