In [1]:
import torch

In [7]:
a = torch.tensor([1,2,3.0],requires_grad=True)
b = torch.tensor([3,8,1.0],requires_grad=True)

In [8]:
c = a @ b
c.retain_grad()
d = c**2
d.backward()

In [15]:
c_grad = 2*c
c.grad, c_grad

(tensor(44.), tensor(44., grad_fn=<MulBackward0>))

In [17]:
a_grad = b * c_grad
a.grad, a_grad

(tensor([132., 352.,  44.]),
 tensor([132., 352.,  44.], grad_fn=<MulBackward0>))

In [18]:
b_grad = a * c_grad
b.grad, b_grad

(tensor([ 44.,  88., 132.]),
 tensor([ 44.,  88., 132.], grad_fn=<MulBackward0>))

In [41]:
a = torch.randn(2,3, requires_grad=True)
b = torch.randn(3,4, requires_grad=True)
c = a @ b  ; c.retain_grad()
e = c.sum(); e.retain_grad() ;e.backward()

In [43]:
c_grad = torch.ones_like(c) * e.grad
c.grad, c_grad

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [46]:
a.grad, b.sum(axis = 1),b.grad, a.sum(axis = 0)

(tensor([[-0.8102,  0.9646, -1.4072],
         [-0.8102,  0.9646, -1.4072]]),
 tensor([-0.8102,  0.9646, -1.4072], grad_fn=<SumBackward1>),
 tensor([[-0.5374, -0.5374, -0.5374, -0.5374],
         [ 0.6819,  0.6819,  0.6819,  0.6819],
         [ 3.8781,  3.8781,  3.8781,  3.8781]]),
 tensor([-0.5374,  0.6819,  3.8781], grad_fn=<SumBackward1>))

In [111]:
a = torch.randn(2,3, requires_grad=True)
b = torch.randn(3,2, requires_grad=True)
c = a @ b  ; c.retain_grad()
d = c**2   ; d.retain_grad()
e = d.sum(); e.retain_grad() ;e.backward()

In [112]:
c_grad = 2*c 

In [113]:
a

tensor([[ 1.0758,  0.4186,  0.4591],
        [-0.5616,  0.4402,  0.0691]], requires_grad=True)

In [114]:
b

tensor([[ 0.1029, -0.4692],
        [ 0.4194, -1.7430],
        [-0.6501,  0.3052]], requires_grad=True)

In [115]:
c

tensor([[-0.0122, -1.0942],
        [ 0.0819, -0.4827]], grad_fn=<MmBackward0>)

In [116]:
a[0]

tensor([1.0758, 0.4186, 0.4591], grad_fn=<SelectBackward0>)

In [117]:
b[:,0]

tensor([ 0.1029,  0.4194, -0.6501], grad_fn=<SelectBackward0>)

In [118]:
a[0] @ b[:,0]

tensor(-0.0122, grad_fn=<DotBackward0>)

In [125]:
c[0][0]

tensor(-0.0122, grad_fn=<SelectBackward0>)

In [124]:
a.grad[0], b[:,0].sum() * c_grad[0][0]

(tensor([ 1.0243,  3.8042, -0.6519]),
 tensor([0.0089, 0.0323, 0.0084], grad_fn=<MulBackward0>))

In [99]:
a = torch.tensor([1,2,3.0],requires_grad=True)
b = torch.tensor([3,8,1.0],requires_grad=True)
c = a @ b; c.retain_grad()
d = c**2; d.retain_grad()
d.backward()

In [56]:
c.grad, 2*c

(tensor(44.), tensor(44., grad_fn=<MulBackward0>))

In [57]:
a.grad, 2*c* b

(tensor([132., 352.,  44.]),
 tensor([132., 352.,  44.], grad_fn=<MulBackward0>))

In [142]:
a = torch.tensor([[1,2,3],[4,5,6.0]],requires_grad=True)
b = torch.tensor([[7,8],[9,10],[11.0,12]],requires_grad=True)
c = ((a@b)); c.retain_grad()
d = c**2; d.retain_grad()
e = d.sum(); e.retain_grad()
e.backward()

In [146]:
c.grad, 2*c

(tensor([[116., 128.],
         [278., 308.]]),
 tensor([[116., 128.],
         [278., 308.]], grad_fn=<MulBackward0>))

tensor([[1836., 2324., 2812.],
        [4410., 5582., 6754.]])